#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npx lint-staged

branch="$(git rev-parse --abbrev-ref HEAD)"

if [ "$branch" = "main" ]; then
  echo "You can't commit directly to \"$branch\" branch"
  exit 1
fi
